on:
    workflow_call:
  
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install systemd lib dependencies
      run: |
        sudo apt update
        sudo apt install -o Acquire::Retries=10 libsystemd-dev

    - name: Allow non-interactive tests to use systemd D-Bus API polkit >=106
      run: |
        cat << EOF | sudo tee /usr/share/polkit-1/rules.d/00-ci.rules
        // Allow any user to manage units.
        // Fall back to implicit authorization otherwise.
        // For more info, see https://www.freedesktop.org/software/systemd/man/latest/org.freedesktop.systemd1.html#Security
        polkit.addRule(function(action, subject) {
            if (action.id == "org.freedesktop.systemd1.manage-units" ||
                action.id == "org.freedesktop.systemd1.manage-unit-files") {
                return polkit.Result.YES;
            }
        });
        EOF
        # sudo chmod 777 /usr/share/polkit-1/rules.d/00-ci.rules

    # End-to-end tests must run sequentially so they don't compete for
    # fixtures, such as when (un)installing systemd unit files.
    - name: E2E tests
      run: go test -run Test_E2E_ -shuffle=on -v ./...
